config/routes.rb
Rails.application.routes.draw do
  
  resources :locations

  resources :items

  resources :submenus

  get 'devise/home', :to => 'home#view_cart'

  get 'store/view_cart'
  get 'home/index'

  resources :restaurants
  get 'index' => 'home#index'
  get 'home/view_rest_orders'
  get 'home/deactivate_order'
  get 'home/activate_order'
  get 'restaurant/view_orders'
  root 'home#index'
  get 'home/place_order'
  get 'home/view_orders'
  get 'home/decrease_quantity'
  get 'home/increase_quantity'
  get 'home/remove_item'
 
  devise_for :users, :controllers => { registrations: 'registrations' }
  post 'home/add_to_cart'
  get 'home/empty_cart'
  post 'home/index'
  get 'home/view_cart'

end

app/models/submenu.rb
class Submenu < ActiveRecord::Base
end

app/controllers/submenus_controller.rb
class SubmenusController < ApplicationController
  before_action :set_submenu, only: [:show, :edit, :update, :destroy]

  # GET /submenus
  # GET /submenus.json
  def index
    @submenus = Submenu.all
  end

  # GET /submenus/1
  # GET /submenus/1.json
  def show
    @restaurant = Restaurant.find(@submenu.restaurantId)
  end

  # GET /submenus/new
  def new
    @submenu = Submenu.new
    @submenu.restaurant = params[:restaurant]
    @submenu.restaurantId = params[:restaurantId]
  end

  # GET /submenus/1/edit
  def edit
  end

  # POST /submenus
  # POST /submenus.json
  def create
    @submenu = Submenu.new(submenu_params)

      respond_to do |format|
        if (@submenu.restaurantId != current_user.try(:restaurantid)) && !current_user.try(:admin?)
          format.html { redirect_to restaurant_path(:id => current_user.try(:restaurantid)), alert: 'There was an error saving your menu.' }
          format.json { render :show, status: :unprocessable_entity, location: @submenu }
        elsif @submenu.save
          format.html { redirect_to restaurant_path(:id => @submenu.restaurantId), notice: 'Menu was successfully created.' }
          format.json { render :show, status: :created, location: @submenu }
        else
          format.html { render :new }
          format.json { render json: @submenu.errors, status: :unprocessable_entity }
        end
      end

  end

  # PATCH/PUT /submenus/1
  # PATCH/PUT /submenus/1.json
  def update
    respond_to do |format|
      if (@submenu.restaurantId != current_user.try(:restaurantid)) && !current_user.try(:admin?)
          format.html { redirect_to restaurant_path(:id => current_user.try(:restaurantid)), alert: 'There was an error saving your menu.' }
          format.json { render :show, status: :unprocessable_entity, location: @submenu }
      elsif @submenu.update(submenu_params)
        format.html { redirect_to @submenu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @submenu }
      else
        format.html { render :edit }
        format.json { render json: @submenu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submenus/1
  # DELETE /submenus/1.json
  def destroy
    @restaurantId = @submenu.restaurantId
    @submenu.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(:id => @restaurantId), notice: 'Menu was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submenu
      @submenu = Submenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submenu_params
      params.require(:submenu).permit(:name, :restaurant, :restaurantId)
    end
end

app/helpers/submenus_helper.rb
module SubmenusHelper
end

app/views/submenus/_form.html.erb
<%= form_for(@submenu) do |f| %>
  <% if @submenu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submenu.errors.count, "error") %> prohibited this submenu from being saved:</h2>

      <ul>
      <% @submenu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div>
    <%= f.hidden_field :restaurant %>
    <%= f.hidden_field :restaurantId %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default btn-sm" %>
  </div>
<% end %>

app/views/submenus/edit.html.erb
<h1>Editing Submenu</h1>

<%= render 'form' %>

<%= link_to 'Show', @submenu %> |
<%= link_to 'Back', restaurant_path(@submenu.restaurantId) %>

app/views/submenus/index.html.erb
<% if current_user.try(:admin?) %>
  <p id="notice"><%= notice %></p>

  <h1>Listing Submenus</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Restaurant</th>
        <th>Restaurantid</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @submenus.each do |submenu| %>
        <tr>
          <td><%= submenu.name %></td>
          <td><%= submenu.restaurant %></td>
          <td><%= submenu.restaurantId %></td>
          <td><%= link_to 'Show', submenu, :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Edit', edit_submenu_path(submenu), :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Destroy', submenu, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<% end %>

app/views/submenus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_path(:id => @submenu.restaurantId) %>

app/views/submenus/show.html.erb
<p>
  <%= image_tag @restaurant.avatar.url(:medium) %>
</p>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<hr>

<h3><%= @submenu.name %></h3>

<% if (current_user.try(:restaurantid) == @submenu.restaurantId) || current_user.try(:admin?) %>
<%= link_to 'Edit Menu', edit_submenu_path(@submenu), :class => 'btn btn-default btn-sm' %> 
  
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

  <% Item.where(submenuId:@submenu.id).find_each do |item| %>
    <tr>
      <td><%=item.name%></td>
      <td><%=number_to_currency(item.price)%></td>
      <% if (current_user.try(:restaurantid) == nil) && (current_user.try(:admin) != true) && user_signed_in? %>
        <td><%= button_to 'Add to Cart', {:controller => :home, :action => 'add_to_cart', :id => item.id, :submenu => @submenu}, :class => "btn btn-default btn-sm"%></td>
      <% end %>
      
      <% if (current_user.try(:restaurantid) == @submenu.restaurantId) || current_user.try(:admin?) %>
          <td><%= link_to 'Edit', edit_item_path(item), :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %></td>
      <% else %>

      <% end %>

    </tr>

  <% end %>

  </tbody>
</table>
<% if (current_user.try(:restaurantid) == @submenu.restaurantId) || current_user.try(:admin?) %>
  <div><%= link_to '+ Add New Item', new_item_path(:submenuId => @submenu.id, :restaurantId => @submenu.restaurantId), :class => "btn btn-default btn-sm"  %></div>
<% end %>

<div><%= link_to 'Back', restaurant_path(@submenu.restaurantId) %></div>