config/routes.rb
Rails.application.routes.draw do
  
  resources :locations

  resources :items

  resources :submenus

  get 'devise/home', :to => 'home#view_cart'

  get 'store/view_cart'
  get 'home/index'

  resources :restaurants
  get 'index' => 'home#index'
  get 'home/view_rest_orders'
  get 'home/deactivate_order'
  get 'home/activate_order'
  get 'restaurant/view_orders'
  root 'home#index'
  get 'home/place_order'
  get 'home/view_orders'
  get 'home/decrease_quantity'
  get 'home/increase_quantity'
  get 'home/remove_item'
 
  devise_for :users, :controllers => { registrations: 'registrations' }
  post 'home/add_to_cart'
  get 'home/empty_cart'
  post 'home/index'
  get 'home/view_cart'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :orders
  has_one :location, dependent: :destroy
  has_attached_file :avatar, :styles => { :medium => "150x150>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  #GET /restaurants/view_orders
  def view_orders
    user = User.find(current_user.try(:id))
    rest = Restaurant.find(user.restaurantId)

    @orders = rest.orders

  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        check_location
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update



    respond_to do |format|
      if @restaurant.update(restaurant_params)
        check_location
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :visible, :description, :logo, :avatar)
    end

    def check_location
    
     if(@restaurant.location == nil)
        @location = Location.create(:address => @restaurant.address)
        @restaurant.location = @location
        @restaurant.save
     elsif(@restaurant.location.address != @restaurant.address)
        @restaurant.location.destroy
        @location = Location.create(:address => @restaurant.address)
        @restaurant.location = @location
        @restaurant.save
     end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => { :multipart => true } do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.file_field :avatar %>
</div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default btn-sm" %>
  </div>
<% end %>

app/views/restaurants/_order.html.erb
<hr>

<% order.order_items.each do |item| %>
<div><%= item.name %></div>
<div><%= item.price %></div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', @restaurant %>

app/views/restaurants/index.html.erb
<% if current_user.try(:admin?) %>

  <h1>Listing Restaurants</h1>

  <table class = "table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Visible</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= restaurant.name %></td>
          <td><%= restaurant.address %></td>
          <td><%= restaurant.visible %></td>
          <td><%= restaurant.description %></td>
          <td><%= link_to 'Show', restaurant, :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), :class => "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Restaurant', new_restaurant_path, :class => "btn btn-default btn-sm"  %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<p>
  <%= image_tag @restaurant.avatar.url(:medium) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>




<table class="table table-hover">
  <thead>
    <tr>
      <th>Menus</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

  <% Submenu.where(restaurantId:@restaurant.id).find_each do |submenu| %>
    <tr>
      <td><%=submenu.name%></td>
      

        <td><%= link_to 'show', submenu, :class => "btn btn-default btn-sm" %></td>

      <% if (current_user.try(:restaurantid) == @restaurant.id) || current_user.try(:admin?) %>
        <td><%= link_to 'Delete', submenu, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %></td>
      <% end %>
    
    </tr>

  <% end %>

  </tbody>
</table>
<% if (current_user.try(:restaurantid) == @restaurant.id) || current_user.try(:admin?) %>
  <%= link_to '+ Add New Menu', new_submenu_path(:restaurant => @restaurant.name, :restaurantId => @restaurant.id), :class => "btn btn-default btn-sm" %>
<% end %>

app/views/restaurants/view_orders.html.erb
	<%= render :partial => 'order', :collection => @orders %>